// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_jB_F7AI2_K_9zk9Eko06Yrpf0cMpU7c',
    appId: '1:432682594880:web:b0fd82333a07b482c325a5',
    messagingSenderId: '432682594880',
    projectId: 'crud-67cd0',
    authDomain: 'crud-67cd0.firebaseapp.com',
    storageBucket: 'crud-67cd0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQPqb97r6daoPoeL8v-pkYwhgv6YcA6MM',
    appId: '1:432682594880:android:dbe08589d6d3aae0c325a5',
    messagingSenderId: '432682594880',
    projectId: 'crud-67cd0',
    storageBucket: 'crud-67cd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQHUMtzgLxW3M6wKnQUIxql7qrnvKqaI',
    appId: '1:432682594880:ios:1e15d185ae359ff7c325a5',
    messagingSenderId: '432682594880',
    projectId: 'crud-67cd0',
    storageBucket: 'crud-67cd0.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNQHUMtzgLxW3M6wKnQUIxql7qrnvKqaI',
    appId: '1:432682594880:ios:1e15d185ae359ff7c325a5',
    messagingSenderId: '432682594880',
    projectId: 'crud-67cd0',
    storageBucket: 'crud-67cd0.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_jB_F7AI2_K_9zk9Eko06Yrpf0cMpU7c',
    appId: '1:432682594880:web:cfa0ff5d0d849470c325a5',
    messagingSenderId: '432682594880',
    projectId: 'crud-67cd0',
    authDomain: 'crud-67cd0.firebaseapp.com',
    storageBucket: 'crud-67cd0.firebasestorage.app',
  );

}